export const ADD_FILTER = "ADD_PRICE_FILTER";
export const REMOVE_PRICE_FILTER = "REMOVE_PRICE_FILTER";
export const REMOVE_METERAGE_FILTER = "REMOVE_METERAGE_FILTER";
export const REMOVE_BUILDIN_FILTER = "REMOVE_BUILDIN_FILTER";
export const REMOVE_ROOM_FILTER = "REMOVE_ROOM_FILTER";
