export const fakeUser = {
  business_license: "0123456789",
  business_name: "ستاره",
  posts: [
    {
      id: 1,
      title: "عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی",
      meterage: 150,
      room: 2,
      buldIn: 1385,
      parking: true,
      wareHouse: true,
      document: true,
      price: 15_500_000,
      information: "09302582971",
      category: "buy",
      description:
        "لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم",
    },
    {
      id: 2,
      title: "عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی",
      meterage: 100,
      room: 1,
      buldIn: 1400,
      parking: false,
      wareHouse: true,
      document: true,
      price: 10_500_000,
      information: "09302582971",
      category: "buy",
      description:
        "لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم",
    },
    {
      id: 3,
      title: "عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی",
      meterage: 250,
      room: 2,
      buldIn: 1385,
      parking: true,
      wareHouse: true,
      document: true,
      trust: 100_000_000,
      rent: 2_000_000,
      information: "09302582971",
      category: "rent",
      description:
        "لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم",
    },
    {
      id: 4,
      title: "عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی",
      meterage: 85,
      room: 2,
      buldIn: 1385,
      parking: true,
      wareHouse: false,
      document: true,
      trust: 200_000_000,
      rent: 0,
      information: "09302582971",
      category: "mortgage",
      description:
        "لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم",
    },
    {
      id: 5,
      title: "عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی",
      meterage: 70,
      room: 3,
      buldIn: 1399,
      parking: false,
      wareHouse: false,
      document: true,
      trust: 250_000_000,
      rent: 0,
      information: "09302582971",
      category: "mortgage",
      description:
        "لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم",
    },
    {
      id: 6,
      title: "عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی",
      meterage: 100,
      room: 1,
      buldIn: 1400,
      parking: false,
      wareHouse: true,
      document: true,
      trust: 110_000_000,
      rent: 1_800_000,
      information: "09302582971",
      category: "rent",
      description:
        "لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم",
    },
    {
      id: 7,
      title: "عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی",
      meterage: 150,
      room: 2,
      buldIn: 1385,
      parking: true,
      wareHouse: false,
      document: true,
      trust: 200_000_000,
      rent: 500_000,
      information: "09302582971",
      category: "rent",
      description:
        "لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم",
    },
    {
      id: 8,
      title: "عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی",
      meterage: 100,
      room: 3,
      buldIn: 1399,
      parking: false,
      wareHouse: false,
      document: true,
      trust: 250_000_000,
      rent: 2_000_000,
      information: "09302582971",
      category: "rent",
      description:
        "لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم",
    },
    {
      id: 9,
      title: "عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی",
      meterage: 200,
      room: 2,
      buldIn: 1385,
      parking: true,
      wareHouse: false,
      document: true,
      price: 11_000_000,
      information: "09302582971",
      category: "buy",
      description:
        "لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم",
    },
    {
      id: 10,
      title: "عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی",
      meterage: 100,
      room: 3,
      buldIn: 1399,
      parking: false,
      wareHouse: false,
      document: true,
      price: 9_000_000,
      information: "09302582971",
      category: "buy",
      description:
        "لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم",
    },
    {
      id: 11,
      title: "عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی",
      meterage: 110,
      room: 2,
      buldIn: 1385,
      parking: true,
      wareHouse: false,
      document: true,
      trust: 200_000_000,
      rent: 0,
      information: "09302582971",
      category: "mortgage",
      description:
        "لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم",
    },
    {
      id: 12,
      title: "عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی",
      meterage: 100,
      room: 3,
      buldIn: 1399,
      parking: false,
      wareHouse: false,
      document: true,
      trust: 250_000_000,
      rent: 0,
      information: "09302582971",
      category: "mortgage",
      description:
        "لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم",
    },
    {
      id: 13,
      title: "عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی",
      meterage: 150,
      room: 2,
      buldIn: 1385,
      parking: true,
      wareHouse: true,
      document: true,
      price: 15_500_000,
      information: "09302582971",
      category: "buy",
      description:
        "لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم",
    },
    {
      id: 14,
      title: "عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی",
      meterage: 100,
      room: 1,
      buldIn: 1400,
      parking: false,
      wareHouse: true,
      document: true,
      price: 10_500_000,
      information: "09302582971",
      category: "buy",
      description:
        "لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم",
    },
    {
      id: 15,
      title: "عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی",
      meterage: 250,
      room: 3,
      buldIn: 1385,
      parking: true,
      wareHouse: true,
      document: true,
      trust: 100_000_000,
      rent: 2_000_000,
      information: "09302582971",
      category: "rent",
      description:
        "لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم",
    },
    {
      id: 16,
      title: "عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی",
      meterage: 85,
      room: 3,
      buldIn: 1385,
      parking: true,
      wareHouse: false,
      document: true,
      trust: 200_000_000,
      rent: 0,
      information: "09302582971",
      category: "mortgage",
      description:
        "لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم",
    },
    {
      id: 17,
      title: "عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی",
      meterage: 70,
      room: 1,
      buldIn: 1399,
      parking: false,
      wareHouse: false,
      document: true,
      trust: 250_000_000,
      rent: 0,
      information: "09302582971",
      category: "mortgage",
      description:
        "لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم",
    },
    {
      id: 18,
      title: "عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی",
      meterage: 100,
      room: 0,
      buldIn: 1400,
      parking: false,
      wareHouse: true,
      document: true,
      trust: 110_000_000,
      rent: 1_800_000,
      information: "09302582971",
      category: "rent",
      description:
        "لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم",
    },
    {
      id: 19,
      title: "عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی",
      meterage: 150,
      room: 2,
      buldIn: 1385,
      parking: true,
      wareHouse: false,
      document: true,
      trust: 200_000_000,
      rent: 500_000,
      information: "09302582971",
      category: "rent",
      description:
        "لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم",
    },
    {
      id: 20,
      title: "عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی",
      meterage: 100,
      room: 3,
      buldIn: 1399,
      parking: false,
      wareHouse: false,
      document: true,
      trust: 250_000_000,
      rent: 2_000_000,
      information: "09302582971",
      category: "rent",
      description:
        "لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم",
    },
    {
      id: 21,
      title: "عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی",
      meterage: 200,
      room: 2,
      buldIn: 1385,
      parking: true,
      wareHouse: false,
      document: true,
      price: 11_000_000,
      information: "09302582971",
      category: "buy",
      description:
        "لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم",
    },
    {
      id: 22,
      title: "عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی",
      meterage: 100,
      room: 3,
      buldIn: 1399,
      parking: false,
      wareHouse: false,
      document: true,
      price: 9_000_000,
      information: "09302582971",
      category: "buy",
      description:
        "لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم",
    },
    {
      id: 23,
      title: "عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی",
      meterage: 110,
      room: 2,
      buldIn: 1385,
      parking: true,
      wareHouse: false,
      document: true,
      trust: 200_000_000,
      rent: 0,
      information: "09302582971",
      category: "mortgage",
      description:
        "لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم",
    },
    {
      id: 24,
      title: "عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی عنوان آگهی",
      meterage: 100,
      room: 3,
      buldIn: 1399,
      parking: false,
      wareHouse: false,
      document: true,
      trust: 250_000_000,
      rent: 0,
      information: "09302582971",
      category: "mortgage",
      description:
        "لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم لورم ایپسوم",
    },
  ],
};
